### ISSUE TITLE
System.MissingMethodException

### ISSUE THREAD

**Issue by hastarin** [marcio-azevedo/serilog-sinks-slack#1]
I'm getting the following exception.

System.MissingMethodException occurred
  HResult=-2146233069
  Message=Method not found: 'System.String FSharp.Data.Http.RequestString(System.String, Microsoft.FSharp.Core.FSharpOption`1<Microsoft.FSharp.Collections.FSharpList`1<System.Tuple`2<System.String,System.String>>>, Microsoft.FSharp.Core.FSharpOption`1<System.Collections.Generic.IEnumerable`1<System.Tuple`2<System.String,System.String>>>, Microsoft.FSharp.Core.FSharpOption`1<System.String>, Microsoft.FSharp.Core.FSharpOption`1<FSharp.Data.HttpRequestBody>, Microsoft.FSharp.Core.FSharpOption`1<System.Collections.Generic.IEnumerable`1<System.Tuple`2<System.String,System.String>>>, Microsoft.FSharp.Core.FSharpOption`1<System.Net.CookieContainer>, Microsoft.FSharp.Core.FSharpOption`1<Boolean>, Microsoft.FSharp.Core.FSharpOption`1<System.String>, Microsoft.FSharp.Core.FSharpOption`1<Microsoft.FSharp.Core.FSharpFunc`2<System.Net.HttpWebRequest,System.Net.HttpWebRequest>>)'.
  Source=SlackClient
  StackTrace:
       at SlackClient.SlackClient.SendMessageViaWebhooks(String webhookUri, String message)
       at Serilog.Sinks.Slack.SlackSink.SendMessageWithWebHooks(String webhookUri, String message)
  InnerException: 

I'll update the issue if I can determine a possible cause because I know I had things working briefly a week ago.

Perhaps there has been a breaking change somewhere.

**Comment by hastarin** [comment]
Just a quick note that I switched to a different package that just works:
https://www.nuget.org/packages/Serilog.Sinks.Slack/

**Comment by marcio-azevedo** [comment]
Can you provide more details, like a sample code to get this error?
Btw, which version of F# and .NET are you running?

**Comment by hastarin** [comment]
Unfortunately no, I didn't have the time to track things further.  I was using whatever the current release version of F# was at the time and .NET 4.6.1

**Comment by marcio-azevedo** [comment]
If you have a sample code to reproduce this error, please share and I'll try to fix the problem.

**Comment by marcio-azevedo** [comment]
If you have a sample code to reproduce this error, please share it and I'll try to fix the problem.

**Comment by fswalker** [comment]
Steps to reproduce the error:

1. Open solution in Visual Studio (my version is 2015)

2. Find Serilog.Sinks.Slack.TestConsoleApp project

3. Update its FSharp.Data Nuget package to the latest version (2.3.2 at the moment)

4. Run the console app - there should be an error visible.

Updating all FSharp.Data Nuget packages in all projects to the latest version (2.3.2) should help.

**Comment by marcio-azevedo** [comment]
Hi All,

Already updated the nuget packages to the latest version. I'm closing this issue.
Let me know if you find anymore problems.
