### ISSUE TITLE
Updating FSharp.Data from 2.2.5 to 2.3.2 stops messages getting through

### ISSUE THREAD

**Issue by NickBarrett** [marcio-azevedo/serilog-sinks-slack#3]
Hi there.

Thanks for this sink. Works great =)

First time I tried it though I installed the nuget package and then immediately updated FSharp.Data from 2.2.5 to 2.3.2. I couldn't get the messages through. Downgraded back to 2.2.5 it worked.

Thanks again =)

**Comment by marcio-azevedo** [comment]
Hi @NickBarrett,

You should update all the projects with the same version of the FSharp.Data package.
That should work (I already tested). If you're running the Script.fsx (inside SlackClient) make sure you update the path to the new package version:

`#r @"../../packages/FSharp.Data.2.3.2/lib/net40/FSharp.Data.dll";;`

I'm closing this issue. Let me know if you find any more problems.

Regards
