### ISSUE TITLE
Dependencies should be updated to require FSharp.Data >= 2.3.1

### ISSUE THREAD

**Issue by fsilva-coolblue** [marcio-azevedo/serilog-sinks-slack#5]
Hey!

When installing this package from NuGet with `Dependency behavior: Lowest`, it installs FSharp.Data version *2.2.5*.
Running my application using this configuration (and using an Incoming Webhook URI), serilog doesn't post anything to Slack.
By enabling breaking on all exceptions, I see that a a `System.MissingMethodException` is thrown, with message:

```
Method not found: 'System.String FSharp.Data.Http.RequestString(System.String, Microsoft.FSharp.Core.FSharpOption`1<Microsoft.FSharp.Collections.FSharpList`1<System.Tuple`2<System.String,System.String>>>, Microsoft.FSharp.Core.FSharpOption`1<System.Collections.Generic.IEnumerable`1<System.Tuple`2<System.String,System.String>>>, Microsoft.FSharp.Core.FSharpOption`1<System.String>, Microsoft.FSharp.Core.FSharpOption`1<FSharp.Data.HttpRequestBody>, Microsoft.FSharp.Core.FSharpOption`1<System.Collections.Generic.IEnumerable`1<System.Tuple`2<System.String,System.String>>>, Microsoft.FSharp.Core.FSharpOption`1<System.Net.CookieContainer>, Microsoft.FSharp.Core.FSharpOption`1<Boolean>, Microsoft.FSharp.Core.FSharpOption`1<System.String>, Microsoft.FSharp.Core.FSharpOption`1<Microsoft.FSharp.Core.FSharpFunc`2<System.Net.HttpWebRequest,System.Net.HttpWebRequest>>, Microsoft.FSharp.Core.FSharpOption`1<Int32>)'.
```

Updating FSharp.Data to at least version `2.3.1` solves the problem.

I believe the NuGet package should be marked as depending on FSharp.Data version `>= 2.3.1` to prevent this issue.

**Comment by marcio-azevedo** [comment]
Thanks for the feedback. I've updated so it should be fine now.

**Comment by fsilva-coolblue** [comment]
Sweet! Thanks for letting me know!
