### ISSUE TITLE
support DNX

### ISSUE THREAD

**Issue by cilerler** [marcio-azevedo/serilog-sinks-slack#6]
This is a feature request to support DotNet Core

**Comment by sturlath** [comment]
Any progress? Realy need this for .net Core...

**Comment by marcio-azevedo** [comment]
Didn't started it yet. Need to take a look to the .NET Core support for F#, since the Slack is in F#.

**Comment by marcio-azevedo** [comment]
Beta release to support DNX is now available here [Serilog.Sinks.Slack.Core](https://www.nuget.org/packages/Serilog.Sinks.Slack.Core/).
Since it uses a different Slack client I've decided to publish as a different package and only incoming webhooks is supported.
