### ISSUE TITLE
Configuring sink using JSON

### ISSUE THREAD

**Issue by FantasticFiasco** [marcio-azevedo/serilog-sinks-slack#8]
Hi!

There is a proposal over at [Serilog.Settings.Configuration](https://github.com/serilog/serilog-settings-configuration/issues/53) where sink developers would be able to specify an extension point specially designed to support JSON configuration. If this is something you would find beneficial for your sink, please give a thumbs up or something. If not, have a nice day and continue being awesome!

**Comment by FantasticFiasco** [comment]
Closing it due to lack of interest.

**Comment by marcio-azevedo** [comment]
Hi, thanks for the feedback. Let me take a look in the next days and I'll get back to you. Meanwhile I'll re-open this.

**Comment by FantasticFiasco** [comment]
Sorry, you shouldn't read it as lack of interest from you. The proposal seems to solve a problem no other sink developer experience, thus it will never be implemented in `Serilog.Settings.Configuration`. That is the reason as to why I closed also this issue.

Have a nice day!

**Comment by marcio-azevedo** [comment]
Not at all! :) All suggestions to improve are welcome!

**Comment by marcio-azevedo** [comment]
Closing this, feel free to re-open, or open a new one if there's more news regarding https://github.com/serilog/serilog-settings-configuration/issues/53.
